### ISSUE TITLE
[Documentation] Setting the cookie

### ISSUE THREAD

**Issue by GrandOurs35** [thecodingmachine/symfony-boilerplate#9]
Hi,
thanks for your work!
Actually, it's not an issue but something more related to the docs.

I'm trying to undertand how your process with authentification.
I see that in your security.yaml you don't configure any authentificator.

But in your webapp, you use the PHPSESSID cookie that is generated by Symfony. How do you do that? ^^

I don't understand very well GraphQL, but on login, i understand that you retrieve the user from your custom user provider but then it's quite mysterious.
In a second time, i understand that you set the cookie header (on the node server) based on the cookie the user have.

If you have any spare time, to explain this part a bit more, it would be very nice
Thank you

**Comment by gulien** [comment]
Hello @GrandOurs35,

> I see that in your security.yaml you don't configure any authenticator.

GraphQLite provides a Symfony Bundle that hooks itself to the Symfony authentication mechanism. So we just tell Symfony how to load our users via the `UserProvider`.

> But in your webapp, you use the PHPSESSID cookie that is generated by Symfony. How do you do that? ^^

On authentication success, Symfony provides a cookie in the response.
The GraphQL client sets this cookie as header to each GraphQL request (see https://github.com/thecodingmachine/symfony-boilerplate/blob/master/src/webapp/nuxt.config.js#L115). 

The only trap here is SSR: the node server does not know the cookies available in the browser, that's why we set the `PHPSESSID` cookie explicitly (see https://github.com/thecodingmachine/symfony-boilerplate/blob/master/src/webapp/store/actions.js#L3).

---

On a side note, this project is still WIP and I have to work on the documentation 😄

**Comment by GrandOurs35** [comment]
Hi,
thanks a lot for your quick and clear answer, i have a better understand now :)
So i will take a look to this bundle.
